name: Deploy to Streamlit

on:
  push:
    branches:
      - api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Streamlit
      run: pip install streamlit

    - name: Deploy Streamlit app
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: streamlit run main.py
